### ISSUE TITLE
Better organisation of file

### ISSUE THREAD

**Issue by natir** [BIG-Tools/bioinfo_format#1]
Maybe we can use this organisation : 

.
├── alignement
│   ├── exemple.bam
│   └── exemple.sam
├── annotation
│   └── exemple.bed
├── LICENSE
├── README.md
├── sequence
│   ├── exemple.fa
│   └── exemple.fastq
└── variant
    └── exemple.vcf

**Comment by dridk** [comment]
I agree !

**Comment by dridk** [comment]
What about  upload teaching course in bioinformatics ? I made one
